// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  version: env['npm_package_version'],
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],
  firebase: {
    apiKey: 'AIzaSyDsyJQdExll5PlkJ_1Svm3tPF7mZlWthf8',
    authDomain: 'prueba-tecnica-js.firebaseapp.com',
    projectId: 'prueba-tecnica-js',
    databaseURL: 'https://prueba-tecnica-js-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-tecnica-js.appspot.com',
    messagingSenderId: '809717649228',
    appId: '1:809717649228:web:57df3b56d82ba3e6ddc9e9',
    measurementId: 'G-147609NZ73',
  },
};

// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {};
